pyInc= '/usr/include/python2.6'
pandaInc= '/usr/include/panda3d'
pandaLib= '/usr/lib/panda3d'

Program(['main.cpp',
         'simu.cpp', 
         'entity.cpp', 
         'grid.cpp', 
         'cell.cpp', 
         'heightfield_displayer.cpp', 
         'controler.cpp',
         'character.cpp',
         'cell_displayer.cpp',
         'drawing_helpers.cpp',
         'world_camera.cpp',
         'model_manager.cpp',
         'level_manager.cpp',
         'level_displayer.cpp',
         'level_loader.cpp',
         'tinyxml/tinyxml.cpp', 
         'tinyxml/tinystr.cpp', 
         'tinyxml/tinyxmlparser.cpp', 
         'tinyxml/tinyxmlerror.cpp',
		 'displayer.cpp', 
		 'character_displayer.cpp', 
		 'displayable.cpp',
		 'global.cpp',
		 'entity_displayer.cpp',
		 'monster.cpp',
		 'level.cpp',
		 'ia.cpp',
		 'event.cpp',
		 'event_manager.cpp'
         ],
	CCFLAGS=['-fPIC', '-O2'],
	CPPPATH=[pyInc, pandaInc],
	LIBPATH=pandaLib,
	LIBS=[	'libp3framework',
		'libpanda',
		'libpandafx',
		'libpandaexpress',
		'libp3dtoolconfig',
		'libp3dtool',
		'libp3pystub',
		'libp3direct'])
